name: create and remove Load Balancer
on: 
  workflow_dispatch:
    inputs:
      action:
        description: 'Create or Remove the Load Balancer'
        type: choice
        required: true
        default: 'create'
        options:
          - create
          - remove
      requesttype_environment:
        type: choice
        required: true
        description: 'Request Type and Environment'
        options:
          - Create New RG in DEV
          - Create New RG in UAT
          - Create New RG in QA
          - Create New RG in PROD
          - Create Existing RG in DEV
          - Create Existing RG in UAT
          - Create Existing RG in QA
          - Create Existing RG in PROD
          - Remove in DEV
          - Remove in UAT
          - Remove in QA
          - Remove in PROD
      location_sku:
        type: choice
        required: true
        description: 'Deployment Location and SKU'
        options:
          - eastus2 Standard
          - uksouth Standard
          - centralus Standard
          - ukwest Standard
          - eastus2 Basic
          - uksouth Basic
          - centralus Basic
          - ukwest Basic
      lb_name:
        description: 'Load Balancer Name'
        required: true
      frontend_ip:
        description: 'Frontend IP Configuration Name'
        required: true
      resource_group_purpose:
        description: 'Resource Group and Purpose'
        required: true
      subnetname_nicnames:
        description: 'Subnet name and NIC names (comma-separated)'
        required: true
      private_ip_and_probe:
        description: 'Private IP address, Probe protocol, Probe port (comma-separated)'
        required: true
      tcp_rules:
        description: 'TCP rule protocol, frontend port, backend port (comma-separated)'
        required: true
      https_rules:
        description: 'HTTPS rule protocol, frontend port (comma-separated)'
        required: true

jobs:
  deploy-lb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy Load Balancer
        if: ${{ inputs.action == 'create' }}
        run: |
          az network lb create --resource-group ${{ inputs.resource_group_purpose.split(' ')[0] }} \
            --name ${{ inputs.lb_name }} --location "${{ inputs.location_sku.split(' ')[0] }}" \
            --frontend-ip-name ${{ inputs.frontend_ip }}
      - name: Remove Load Balancer
        if: ${{ inputs.action == 'remove' }}
        run: |
          az network lb delete --resource-group ${{ inputs.resource_group_purpose.split(' ')[0] }} \
            --name ${{ inputs.lb_name }}
